[build]
  publish = "dist/pilates-web-app"
  command = "npm run build"

[build.environment]
  NETLIFY_API_URL = "https://amopilatesgaiman.somee.com/api"
  NETLIFY_ENVIRONMENT = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 